name: Unity WebGL CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-webgl:
    name: Build WebGL
    runs-on: ubuntu-latest

    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Project/PuzzleEngineSandbox/Library
          key: Library-${{ runner.os }}-${{ hashFiles('Project/PuzzleEngineSandbox/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          projectPath: Project/PuzzleEngineSandbox
          unityVersion: 2022.3.0f1
          targetPlatform: WebGL

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebGLBuild
          path: build/WebGL
